### ISSUE TITLE
Can not login to Zengge cloud [list index out of range]

### ISSUE THREAD

**Issue by dilpish** [SleepyNinja0o/home-assistant-zengge#4]
:)
login&password is ok for app

**Comment by SleepyNinja0o** [comment]
It could be using the wrong server. Right now it's defaulting to US servers (which is what I've been using during development).

**Comment by SleepyNinja0o** [comment]
@dilpish 
I have added a new country option to the config flow. Please update and try again =)

**Comment by dilpish** [comment]
cool it's really works)) 

These lamps sat on the shelf for a year, waiting to be installed. Without HA I didn’t need them)

Bluetooth is really weak)

Thanks a lot!

**Comment by SleepyNinja0o** [comment]
You're welcome! Yeah I've noticed the same thing with my lights. Got to keep them really close or they starr disconnecting a lot.
